### ISSUE TITLE
Move away from poetry?

### ISSUE THREAD

**Issue by robertdstein** [simeonreusch/planobs#89]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to use planobs as a dependency, because the poetry dependency requirements are very strict. It makes it hard to ensure compatibility with other projects. 

In general, the poetry model is great for a final-level analysis code which should be exactly reproducible, but bad for generic utility packages which are imported by a lot of other packages. It seems like planobs is in the second category, with three downstream packages so far.

**Describe the solution you'd like**
I would think the package could be more widely/easily used if either the poetry requirements were substantially loosened, or the entire dependency system was moved to setuptools with minimal constraints on e.g python version <3.12, or pandas ==1.4.x 

**Describe alternatives you've considered**
This might be out of scope, because the package does it's core function fine as is. So things could be left as they are.

**Comment by simeonreusch** [comment]
Gotcha, I loosened the requirements significantly, please check if that solves your issues. 
I assume it was the pandas bump to `2.0` that clashed, right? If not, could you point me to what still conflicts with your setup?

**Comment by robertdstein** [comment]
Nope, that was it. Thanks!
